#pragma once

#include <cstdint>
#include <rgfw.hpp>

enum class KeyCode : uint8_t
{
    Nil = RGFW_keyNULL,
    Escape = RGFW_escape,
    Backtick = RGFW_backtick,

    _0 = RGFW_0,
    _1 = RGFW_1,
    _2 = RGFW_2,
    _3 = RGFW_3,
    _4 = RGFW_4,
    _5 = RGFW_5,
    _6 = RGFW_6,
    _7 = RGFW_7,
    _8 = RGFW_8,
    _9 = RGFW_9,

    Minus = RGFW_minus,
    Equal = RGFW_equal,
    Equals = RGFW_equals,
    BackSpace = RGFW_backSpace,
    Tab = RGFW_tab,
    Space = RGFW_space,

    A = RGFW_a,
    B = RGFW_b,
    C = RGFW_c,
    D = RGFW_d,
    E = RGFW_e,
    F = RGFW_f,
    G = RGFW_g,
    H = RGFW_h,
    I = RGFW_i,
    J = RGFW_j,
    K = RGFW_k,
    L = RGFW_l,
    M = RGFW_m,
    N = RGFW_n,
    O = RGFW_o,
    P = RGFW_p,
    Q = RGFW_q,
    R = RGFW_r,
    S = RGFW_s,
    T = RGFW_t,
    U = RGFW_u,
    V = RGFW_v,
    W = RGFW_w,
    X = RGFW_x,
    Y = RGFW_y,
    Z = RGFW_z,

    Period = RGFW_period,
    Comma = RGFW_comma,
    Slash = RGFW_slash,
    Bracket = RGFW_bracket,
    CloseBracket = RGFW_closeBracket,
    Semicolon = RGFW_semicolon,
    Apostrophe = RGFW_apostrophe,
    BackSlash = RGFW_backSlash,
    Ret = RGFW_return,
    Enter = RGFW_enter,
    Del = RGFW_delete,

    F1 = RGFW_F1,
    F2 = RGFW_F2,
    F3 = RGFW_F3,
    F4 = RGFW_F4,
    F5 = RGFW_F5,
    F6 = RGFW_F6,
    F7 = RGFW_F7,
    F8 = RGFW_F8,
    F9 = RGFW_F9,
    F10 = RGFW_F10,
    F11 = RGFW_F11,
    F12 = RGFW_F12,
    F13 = RGFW_F13,
    F14 = RGFW_F14,
    F15 = RGFW_F15,
    F16 = RGFW_F16,
    F17 = RGFW_F17,
    F18 = RGFW_F18,
    F19 = RGFW_F19,
    F20 = RGFW_F20,
    F21 = RGFW_F21,
    F22 = RGFW_F22,
    F23 = RGFW_F23,
    F24 = RGFW_F24,
    F25 = RGFW_F25,

    CapsLock = RGFW_capsLock,
    ShiftL = RGFW_shiftL,
    ControlL = RGFW_controlL,
    AltL = RGFW_altL,
    SuperL = RGFW_superL,
    ShiftR = RGFW_shiftR,
    ControlR = RGFW_controlR,
    AltR = RGFW_altR,
    SuperR = RGFW_superR,

    Up = RGFW_up,
    Down = RGFW_down,
    Left = RGFW_left,
    Right = RGFW_right,
    Insert = RGFW_insert,

    Menu = RGFW_menu,
    End = RGFW_end,
    Home = RGFW_home,
    PageUp = RGFW_pageUp,
    PageDown = RGFW_pageDown,
    NumLock = RGFW_numLock,

    KeyPad_Slash = RGFW_kpSlash,
    KeyPad_Multiply = RGFW_kpMultiply,
    KeyPad_Plus = RGFW_kpPlus,
    KeyPad_Minus = RGFW_kpMinus,
    KeyPad_Equal = RGFW_kpEqual,
    KeyPad_Equals = RGFW_kpEquals,
    KeyPad_1 = RGFW_kp1,
    KeyPad_2 = RGFW_kp2,
    KeyPad_3 = RGFW_kp3,
    KeyPad_4 = RGFW_kp4,
    KeyPad_5 = RGFW_kp5,
    KeyPad_6 = RGFW_kp6,
    KeyPad_7 = RGFW_kp7,
    KeyPad_8 = RGFW_kp8,
    KeyPad_9 = RGFW_kp9,
    KeyPad_0 = RGFW_kp0,
    KeyPad_Period = RGFW_kpPeriod,
    KeyPad_Return = RGFW_kpReturn,

    ScrollLock = RGFW_scrollLock,
    PrintScreen = RGFW_printScreen,
    Pause = RGFW_pause,
    World1 = RGFW_world1,
    World2 = RGFW_world2,
};

enum class KeyState : uint8_t
{
    None = 0,
    Released = 1,
    Pressed = 2,
    Held = 3
};

enum class MouseButton : uint8_t
{
    MouseLeft = RGFW_mouseLeft,
    MouseMiddle = RGFW_mouseMiddle,
    MouseRight = RGFW_mouseRight,

    Mouse0 = MouseLeft,
    Mouse1 = MouseLeft,
    Mouse2 = MouseLeft,
    Mouse3 = RGFW_mouseMisc1,
    Mouse4 = RGFW_mouseMisc2,
    Mouse5 = RGFW_mouseMisc3,
    Mouse6 = RGFW_mouseMisc4,
    Mouse7 = RGFW_mouseMisc5,
};